'use strict';
const $=id=>document.getElementById(id);
const fragment=new URLSearchParams(location.hash.slice(1));
if(fragment.get('key')){sessionStorage.setItem('hornbill-key',fragment.get('key'));history.replaceState(null,'',location.pathname+location.search);}
const key=sessionStorage.getItem('hornbill-key')||'';
let selected=sessionStorage.getItem('hornbill-save')||'',current=null,busy=false,lastJob=0,lastPhase='',imageId=null,imageUrl=null,saveList=[];
function node(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function notice(message){$('notice').textContent=message||'';$('notice').hidden=!message;for(const n of document.querySelectorAll('.dialog-notice'))n.remove();const dialog=document.querySelector('dialog[open]');if(message&&dialog){const n=node('p','notice dialog-notice',message);n.setAttribute('role','alert');dialog.prepend(n);}}
async function api(path,body,method){const r=await fetch('/api/'+path,{method:method||(body?'POST':'GET'),headers:{Authorization:'Bearer '+key,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const text=await r.text();let data;try{data=JSON.parse(text);}catch{data={error:text};}if(!r.ok)throw Error(data.error||'Unable to complete this request.');return data;}
const safe=fn=>async event=>{try{await fn(event);}catch(e){notice(e.message);}};
function controls(){document.querySelectorAll('.choice').forEach(b=>b.disabled=busy);$('continue-button').disabled=busy||!current;$('illustrate-button').disabled=busy||!current?.state.current_scene;$('progress').hidden=!busy;}
async function listSaves(){const result=await api('saves');saveList=result.saves;$('saves').replaceChildren();for(const s of saveList){const b=node('button','save'+(s.id===selected?' selected':''));b.append(node('strong','',s.title),node('span','',s.turn?'Turn '+s.turn:'Not yet begun'));b.onclick=safe(()=>selectSave(s.id));$('saves').append(b);}if(!selected||!saveList.some(s=>s.id===selected))selected=saveList[0]?.id||'';}
async function selectSave(id){selected=id;sessionStorage.setItem('hornbill-save',id);notice('');await refresh();await listSaves();}
async function refresh(){if(!selected){current=null;controls();return;}current=await api('state/'+encodeURIComponent(selected));render();}
async function showImage(image){if(image?.attempt_id===imageId)return;imageId=image?.attempt_id||null;$('scene-image').hidden=true;$('image-placeholder').hidden=false;if(imageUrl){URL.revokeObjectURL(imageUrl);imageUrl=null;}if(!image)return;const expected=imageId;const r=await fetch('/api/image/'+image.attempt_id,{headers:{Authorization:'Bearer '+key}});if(!r.ok)return;const blob=await r.blob();if(imageId!==expected)return;imageUrl=URL.createObjectURL(blob);$('scene-image').src=imageUrl;$('scene-image').hidden=false;$('image-placeholder').hidden=true;}
function render(){const s=current.state,t=current.turn;const title=saveList.find(v=>v.id===selected)?.title||'Your story';$('story-title').textContent=title;$('chapter').textContent=s.turn?'THE STORY CONTINUES':'AT THE EDGE OF A MYSTERY';$('turn-label').textContent=s.turn?'Turn '+s.turn:'Your first move';$('place').textContent=s.locations[s.world.location].name;$('scene-time').textContent=s.world.time+' · '+s.world.weather;$('narration').textContent=t?.narration||s.summary;$('dialogue').replaceChildren();for(const d of t?.dialogue||[]){const block=node('div','speech');block.append(node('strong','',s.characters[d.speaker]?.name||d.speaker),node('p','',d.text));$('dialogue').append(block);}const choices=t?.choices||['I inspect the radio and ask Mira what she recognizes about the transmission.','I look for a practical way into the observatory.'];$('choices').replaceChildren();choices.forEach((text,i)=>{const b=node('button','choice');b.append(node('em','',String(i+1).padStart(2,'0')),node('span','',text));b.onclick=safe(()=>advance(text));$('choices').append(b);});$('image-label').hidden=!current.image;$('image-label').textContent=current.image?.turn<s.turn?'Previous illustration':current.image?.reason==='reused'?'Illustration reused':'Made here, for this scene';void showImage(current.image).catch(e=>notice(e.message));controls();}
async function advance(action){if(!current||busy)return;notice('');await api('turn/'+selected,{action,expected_turn:current.state.turn});$('action').value='';busy=true;$('phase').textContent='Writing the next scene…';$('elapsed').textContent='Starting…';controls();}
async function poll(){try{const j=await api('job');const wasBusy=busy;busy=j.running;$('phase').textContent=j.phase||'Creating your scene…';const seconds=j.started_ms?Math.max(0,Math.floor((Date.now()-j.started_ms)/1000)):0;$('elapsed').textContent=seconds>=60?Math.floor(seconds/60)+'m '+seconds%60+'s elapsed':seconds+'s elapsed';controls();if(j.id&&(lastJob!==j.id||lastPhase!==j.phase||wasBusy&&!busy)){lastJob=j.id;lastPhase=j.phase;await refresh();await listSaves();if(!busy&&j.error)notice(j.error);}}catch(e){notice(e.message);}finally{setTimeout(poll,busy?1000:4000);}}
$('action-form').onsubmit=safe(async e=>{e.preventDefault();await advance($('action').value.trim());});$('action').onkeydown=e=>{if(e.key==='Enter'&&(e.metaKey||e.ctrlKey)){e.preventDefault();$('action-form').requestSubmit();}};
$('illustrate-button').onclick=safe(async()=>{notice('');await api('illustrate/'+selected,{expected_turn:current.state.turn});busy=true;$('phase').textContent='Creating illustration…';$('elapsed').textContent='Starting…';controls();});
$('cancel-button').onclick=safe(()=>api('cancel',{}));
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>$(b.dataset.close).close();
for(const id of ['new-button','new-bottom','new-top'])$(id).onclick=()=>{notice('');$('new-dialog').showModal();};
$('new-form').onsubmit=safe(async e=>{e.preventDefault();const result=await api('saves',{title:$('new-title').value.trim(),premise:$('new-premise').value.trim()||null});$('new-dialog').close();await listSaves();await selectSave(result.id);});
$('settings-button').onclick=()=>{if(!current){$('new-dialog').showModal();return;}const p=current.preferences;$('model').value=p.model;$('image-policy').value=p.image_policy;$('image-size').value=p.image.width+'x'+p.image.height;$('image-seed').value=p.image.seed;$('settings-dialog').showModal();};
$('settings-form').onsubmit=safe(async e=>{e.preventDefault();const [width,height]=$('image-size').value.split('x').map(Number);await api('preferences/'+selected,{...current.preferences,model:$('model').value,image_policy:$('image-policy').value,image:{...current.preferences.image,width,height,seed:Number($('image-seed').value)}},'PUT');$('settings-dialog').close();await refresh();notice('Preferences saved.');});
$('journal-button').onclick=()=>{if(!current)return;const s=current.state;$('summary').textContent=s.summary;$('inventory').replaceChildren(...Object.entries(s.inventory).map(([name,count])=>node('li','',name.replaceAll('_',' ')+' × '+count)));$('threads').replaceChildren(...Object.values(s.plot_threads).filter(t=>t.status==='open').map(t=>node('li','',t.description)));$('director-note').value=s.director_note||'';$('world-notes').value=s.lorebook.map(n=>n.text).join('\n\n');$('reference-entity').replaceChildren(...[...Object.values(s.characters),...Object.values(s.locations)].map(v=>new Option(v.name+(s.references[v.id]?' · reference attached':''),v.id)));$('journal-dialog').showModal();};
$('notes-form').onsubmit=safe(async e=>{e.preventDefault();const lorebook=$('world-notes').value.split(/\n\s*\n/).map(t=>t.trim()).filter(Boolean).map((text,i)=>({id:'note_'+i,text,tags:[]}));await api('notes/'+selected,{director_note:$('director-note').value.trim()||null,lorebook},'PUT');await refresh();$('journal-dialog').close();notice('Story notes saved.');});
$('reference-form').onsubmit=safe(async e=>{e.preventDefault();const file=$('reference-file').files[0];if(!file)return;const bitmap=await createImageBitmap(file);const scale=Math.min(1,1536/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));const r=await fetch('/api/reference/'+selected+'/'+$('reference-entity').value,{method:'POST',headers:{Authorization:'Bearer '+key},body:blob});if(!r.ok){const d=await r.json();throw Error(d.error||'Reference could not be saved.');}await refresh();$('journal-dialog').close();notice('Visual reference attached. It will guide the next illustration.');});
$('export-button').onclick=safe(async()=>{const data=await api('export/'+selected);const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=selected+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
(async()=>{try{await listSaves();if(selected)await selectSave(selected);else $('new-dialog').showModal();await poll();}catch(e){notice(e.message);}})();
